function OAS_RICH(position) {
if (position == 'Middle2') {
document.write ('<!--  Rubicon Project Tag -->\n');
document.write ('<!--  Site: guardian.co.uk (ROW)   Zone: Tech BTF MPU   Size: Medium Rectangle  -->\n');
document.write ('<script language="JavaScript" type="text/javascript">\n');
document.write ('var rp_account   = ');
document.write ("'");
document.write ('7845');
document.write ("'");
document.write (';\n');
document.write ('var rp_site      = ');
document.write ("'");
document.write ('12580');
document.write ("'");
document.write (';\n');
document.write ('var rp_zonesize  = ');
document.write ("'");
document.write ('26805-15');
document.write ("'");
document.write (';\n');
document.write ('var rp_adtype    = ');
document.write ("'");
document.write ('js');
document.write ("'");
document.write (';\n');
document.write ('var rp_smartfile = ');
document.write ("'");
document.write ('[SMART FILE URL]');
document.write ("'");
document.write (';\n');
document.write ('var rp_kw        = ');
document.write ("'");
document.write ('[INSERT KEYWORD HERE]');
document.write ("'");
document.write (';\n');
document.write ('</script>\n');
document.write ('<script type="text/javascript" src="http://ads.rubiconproject.com/ad/7845.js"></script>\n');
document.write ('\n');
document.write ('<IMG SRC="http://oas.guardian.co.uk/5/www.guardian.co.uk/technology/2012/feb/29/raspberry-pi-computer-sale-british/oas.html/L29/882268811/Middle2/Guardian/Rubicon_ROW_Technology_OCTDEC12/SmartTags_ROW_Tech_BTF-MPU.html/573379764f6c43617236594141364457?_RM_EMPTY_&k=raspberry-pi&k=education&k=computing&k=technology&k=software&k=internet&k=linux&k=uk&cf=corporate+it&pid=&ct=article&pt=article&a=&&qc=D&wl10341=&wl10342=&" WIDTH=1 HEIGHT=1>');
}
if (position == 'Right1') {
document.write ('<!--  Rubicon Project Tag -->\n');
document.write ('<!--  Site: guardian.co.uk (ROW)   Zone: Tech   Size: Medium Rectangle  -->\n');
document.write ('<script language="JavaScript" type="text/javascript">\n');
document.write ('var rp_account   = ');
document.write ("'");
document.write ('7845');
document.write ("'");
document.write (';\n');
document.write ('var rp_site      = ');
document.write ("'");
document.write ('12580');
document.write ("'");
document.write (';\n');
document.write ('var rp_zonesize  = ');
document.write ("'");
document.write ('22638-15');
document.write ("'");
document.write (';\n');
document.write ('var rp_adtype    = ');
document.write ("'");
document.write ('js');
document.write ("'");
document.write (';\n');
document.write ('var rp_smartfile = ');
document.write ("'");
document.write ('[SMART FILE URL]');
document.write ("'");
document.write (';\n');
document.write ('var rp_kw        = ');
document.write ("'");
document.write ('[INSERT KEYWORD HERE]');
document.write ("'");
document.write (';\n');
document.write ('</script>\n');
document.write ('<script type="text/javascript" src="http://ads.rubiconproject.com/ad/7845.js"></script>\n');
document.write ('<IMG SRC="http://oas.guardian.co.uk/5/www.guardian.co.uk/technology/2012/feb/29/raspberry-pi-computer-sale-british/oas.html/L29/477827365/Right1/Guardian/Rubicon_ROW_Technology_OCTDEC12/SmartTags_ROW_Tech_MPU1.html/573379764f6c43617236594141364457?_RM_EMPTY_&k=raspberry-pi&k=education&k=computing&k=technology&k=software&k=internet&k=linux&k=uk&cf=corporate+it&pid=&ct=article&pt=article&a=&&qc=D&wl10341=&wl10342=&" WIDTH=1 HEIGHT=1>');
}
if (position == 'Top') {
document.write ('<!--  Rubicon Project Tag -->\n');
document.write ('<!--  Site: guardian.co.uk (ROW)   Zone: Tech   Size: Leaderboard  -->\n');
document.write ('<script language="JavaScript" type="text/javascript">\n');
document.write ('var rp_account   = ');
document.write ("'");
document.write ('7845');
document.write ("'");
document.write (';\n');
document.write ('var rp_site      = ');
document.write ("'");
document.write ('12580');
document.write ("'");
document.write (';\n');
document.write ('var rp_zonesize  = ');
document.write ("'");
document.write ('22638-2');
document.write ("'");
document.write (';\n');
document.write ('var rp_adtype    = ');
document.write ("'");
document.write ('js');
document.write ("'");
document.write (';\n');
document.write ('var rp_smartfile = ');
document.write ("'");
document.write ('[SMART FILE URL]');
document.write ("'");
document.write (';\n');
document.write ('var rp_kw        = ');
document.write ("'");
document.write ('[INSERT KEYWORD HERE]');
document.write ("'");
document.write (';\n');
document.write ('</script>\n');
document.write ('<script type="text/javascript" src="http://ads.rubiconproject.com/ad/7845.js"></script><IMG SRC="http://oas.guardian.co.uk/5/www.guardian.co.uk/technology/2012/feb/29/raspberry-pi-computer-sale-british/oas.html/L29/1327260139/Top/Guardian/Rubicon_ROW_Technology_OCTDEC12/SmartTags_ROW_Tech_LB.html/573379764f6c43617236594141364457?_RM_EMPTY_&k=raspberry-pi&k=education&k=computing&k=technology&k=software&k=internet&k=linux&k=uk&cf=corporate+it&pid=&ct=article&pt=article&a=&&qc=D&wl10341=&wl10342=&" WIDTH=1 HEIGHT=1>');
}
if (position == 'x31') {
document.write ('<script>var sponJSON = {"ad":{"title":"Sponsored feature","image":"http://static.guim.co.uk/sys-images/Guardian/Pix/commercial/2012/9/10/1347290943791/HiFX-money-transfers---il-001.jpg","alt-image-text":"illustration of earth and £ note","link":"http://oas.guardian.co.uk/5c/www.guardian.co.uk/technology/2012/feb/29/raspberry-pi-computer-sale-british/oas.html/L29/1119825951/x31/Guardian/HiFX_March12_March13_SF_Filler_EU_ROS/HiFX_March12_March13_SF_Filler_EU_ROS_NewCreative.html/573379764f6c43617236594141364457?http://www.hifxonline.co.uk/registration/default.aspx?_dfxid=102245","linkText":"Need to transfer money overseas?","description":"Find out how others have saved money and got the best deal. Plus, win a £25 M&S voucher"}}</script>');
}
}
